# Generated by Django 5.0 on 2024-01-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SomeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "SomeModels",
                "ordering": ("title",),
            },
        ),
    ]
